### ISSUE TITLE
packages/backend build: Error: ENOENT: no such file or directory, lstat '/app/packages/backend/src/config'

### ISSUE THREAD

**Issue by xinmans** [tortorse/beancount-analysis-web#1]
pnpm -r run build

Scope: 2 of 3 workspace projects
packages/backend build$ tsc && npm run copy-config
packages/frontend build$ vue-tsc && vite build
packages/backend build: > backend@1.0.0 copy-config
packages/backend build: > ncp src/config dist/config
packages/backend build: There were errors during the copy.
packages/backend build: Error: ENOENT: no such file or directory, lstat '/app/packages/backend/src/config'
packages/backend build: Failed
undefined
/app/packages/backend:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  backend@1.0.0 build: `tsc && npm run copy-config`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
The command '/bin/sh -c pnpm run build' returned a non-zero code: 1
ERROR: Service 'app' failed to build : Build failed

**Comment by tortorse** [comment]
fixed
